export enum ICON_NAMES {
  OPEN_EYE = 'eye',
  CLOSED_EYE = 'eye-with-line',
  VERIFIED = 'verified',
  HOME = 'home',
  SEARCH = 'search1',
  CALENDAR = 'calendar',
  SHOPPING_CART = 'cart-outline',
  ELLIPSIS = 'md-ellipsis-vertical',
  DOG_PAW = 'md-paw-sharp',
  DOG = 'dog',
  USER = 'person-sharp',
  APPLE_LOGO = 'apple',
  GOOGLE_LOGO = 'google',
  CARET_DOWN = 'chevron-down',
  SUCCESS = 'check-circle',
  ERROR = 'times-circle',
  WARN = 'exclamation-triangle',
  INFO = 'info-circle'
}